### ISSUE TITLE
some design remarks

### ISSUE THREAD

**Issue by pat-cki** [fac18/week2-CEFG-To-do#12]
🥳 I really like the overall feeling of your page and the colour palette you used. It is really great!

🤔From the UX perspective maybe it would make more sense to place the input above the todos list, as it represents the main functionality on the page.

Also I was wondering if using the black colour for icons in the buttons is the right way. To have a better contrast I would probably go with white.

**Comment by redahaq** [comment]
Totally agree.. it also means the input field won't disappear below the fold if the Todo list is super long.

I'd also love if the input was slightly scaled up in size as, like Pat says, it is the primary functionality.

**Comment by roshlarosh** [comment]
Thank you guys for your advices 💃
