### ISSUE TITLE
Layout in mobile mode

### ISSUE THREAD

**Issue by bethanyios** [fac18/week2-CEFG-To-do#16]
I had a fiddle with the mobile view and it messes with your background and button layout etc - you probably know this but just pointing it out so you can reference this issue as a todo task 😉

**Comment by redahaq** [comment]
This is an interesting one as it renders perfectly for both Pat and me on mobile view in Chrome dev tools. But it's doing a weird cascadey thing with the buttons for Beth and Dan. WEIRD!

**Comment by bethanyios** [comment]
Very weird!!

Here is a picture of what my inspect is showing 
![Screen Shot 2019-11-08 at 10 46 26](https://user-images.githubusercontent.com/36175966/68471023-32519e80-0215-11ea-91bd-9d85d46d8982.png)

**Comment by redahaq** [comment]
Should be noted we selected the same devices to make sure we were comparing like for like!

**Comment by pat-cki** [comment]
Maybe reseting css would help here. 

In the previous project we had a quite similar issue nad using reset.css did the job. 

We used the one from the [link](https://hankchizljaw.com/wrote/a-modern-css-reset/)

**Comment by jdy3** [comment]
Thanks for the feedback guys, hopefully it looks better now :)
