### ISSUE TITLE
a11y!

### ISSUE THREAD

**Issue by redahaq** [fac18/week2-CEFG-To-do#21]
We forgot to do this til pretty late in the game, so no judgement! A quick accessibility audit and minor fixes will make all the difference in making your app available to all!

![image](https://user-images.githubusercontent.com/39345463/68471674-95900080-0216-11ea-89b6-8c5a7b63b0a5.png)

**Comment by roshlarosh** [comment]
Relates #20 
Fixed the accessibility issues
