### ISSUE TITLE
You sure know how to test to impress...

### ISSUE THREAD

**Issue by bobbysebolao** [fac18/week2-CEFG-To-do#22]
Ability to add todos?  ✅
Ability to mark todos as done?  ✅
Ability to delete todos?  ✅
Jazzy background image?  ✅✅✅

Your project looks great! From a UX standpoint, I especially like the subtle visual feedback that indicates when a todo has been marked as done (I think opacity is a great way to show that a UI element is inactive.

And most importantly, you've got a super suit of tests! I totally agree that testing is a bit counter intuitive at first (trial and error is definitely the name of the game!), but you've done a great job of getting to grips with it. Well done, you should all be really chuffed!

![bart](http://giphygifs.s3.amazonaws.com/media/4oMoIbIQrvCjm/giphy.gif)

**Comment by redahaq** [comment]
So agree!!

**Comment by roshlarosh** [comment]
Thank you bobby :D
