### ISSUE TITLE
Branch and commit distro

### ISSUE THREAD

**Issue by freemvmt** [fac18/week2-CEFG-To-do#27]
Some nice granular commits and several distinct branches to break up the work/git flow.

Only thing I noticed is that Rosa only committed merges and README edits and didn't push any branches - so maybe make sure to work from everyone's computer for a least one branch?

**Comment by marialani** [comment]
We had intended to share commits using a method shared with us from a previous FaC member. Although, as noted we hadn't gotten around to doing so.
